.TH ШЭТ 1
.SH ИМЯ
ШЭТ \- широкоформатная электронная таблица
.SH ФОРМАТ
.B sc
.I "sc [-] [-a] [-b] [-m] [-l] [-r#] [-c#] [файл]"
.SH ОПИСАНИЕ
В основе табличного процессора
.I ШЭТ
лежит "электронная таблица", разделенная на столбцы, строки и клетки.
Каждая клетка может содержать текстовую строку, число или формулу,
использующую в качестве операндов значения других клеток.
По умолчанию размер таблицы равен 64\ строкам по вертикали и
16\ столбцам по горизонтали. Его можно задавать флагами:
.IP -r<число>
определяет размер таблицы по вертикали в строках. Аргумент <число>
должен находиться в диапазоне от 1 до 32768.
.IP -с<число>
определяет размер таблицы по горизонтали в столбцах. Аргумент -
в диапазоне от 1 до 702.
.PP
При вызове
.B ШЭТ
загружает таблицу из файла с именем, указанным в качестве
аргумента, а если аргумент не задан - то из файла "workfile".
К имени автоматически добавляется суффикс ".sc".
.PP
Можно задавать следующие флаги:
.IP -
не считывать файл "workfile.sc"
.IP -a
отключить режим автоматического перевычисления
.IP -b
отключить отображение границ окна, подсказки и строки состояния
.IP -m
для цветных терминалов - не использовать цвета, работать в черно-белом режиме
.IP -l
переключить режим команд и диагностических сообщений.
В ШЭТ есть три режима:
1-й - английские сообщения, английские команды,
2-й - русские сообщения, английские команды,
3-й - русские сообщения, русские команды.
Режим по умолчанию зависит от глобальной переменной MSG: если MSG=r,
то устанавливается 2-й режим, иначе - 1-й.
.PP
Строки пронумерованы целыми числами, начиная с 0, а столбцы - латинскими
буквами A-Z, AA-ZZ. Для ссылки на клетку нужно указать номер
столбца и строки, в которой она находится, например, A0, BF54.
.PP
Если при вычислении формулы была ошибка (например, деление на 0),
то результат вычисления выдается в виде "??".
.PP
По таблице можно передвигаться, используя стрелки и команды
управления курсором. Текущая клетка выделяется инверсией или
квадратными скобками.
.PP
Для перемещения по таблице служат команды:
.IP "^L или стрелка влево"
влево на одну клетку
.IP "^R или стрелка вправо"
вправо на одну клетку
.IP "^U или стрелка вверх"
вверх на одну клетку
.IP "^D или стрелка вниз"
вниз на одну клетку
.IP "^Y или <Home>"
влево на ширину окна
.IP "^Z или <End>"
вправо на ширину окна
.IP "^K или <Page Up>"
вверх на высоту окна
.IP "^B или <Page Down>"
вниз на высоту окна
.PP
Для введения в таблицу новых формул, а также для редактирования значений
служит командный режим. Переход в него и обратно
осуществляется нажатием клавиши ^I (Tab).
.PP
В режиме ввода можно извлекать содержимое ячеек с помощью следующих команд:
.IP "^V"
ввести числовое значение текущей ячейки
.IP "^F"
ввести формулу из текущей ячейки
.IP "^T"
ввести текст из текущей ячейки
.IP "^A"
ввести имя текущей ячейки
.PP
Из режима ввода можно перейти в режим редактирования командой "^E".
В режиме редактирования выполняются следующие команды:
.IP "^M или <Return>"
выйти из режима редактирования
.IP "^L или стрелка влево"
влево на один символ
.IP "^R или стрелка вправо"
вправо на один символ
.IP "^D или стрелка вниз"
удалить текущий символ
.гIP "^U или стрелка вверх"
вставить удаленный символ
.IP "^I или <Tab>"
перейти в конец или в начало строки
.PP
Сервисные команды:
.IP "^X"
обновить экран
.IP "^С"
отказаться от выполнения текушей команды
.IP "^P"
выдать краткую инструкцию по работе в
.B ШЭТ
.IP "^G"
нарисовать график
.PP
Командный режим построен на основе меню.
Текущее меню высвечивается на второй строке снизу.
Чтобы выбрать нужную команду, надо нажать клавишу, которая
выделена в имени команды большой буквой. Если после имени
команды в меню стоит символ "/", значит это - переход на следующий уровень
меню. Для передвижения по меню служа также команды:
.IP "^M или <Return>"
вернуться на предыдущий уровень меню
.IP "/"
вернуться на верхний уровень меню
.PP
Каждая команда однозначно определяется так называемым полным именем
команды. Оно состоит из собственно имени команды
и имен всех меню, ведущих к ней, разделенных символом "/",
например, "/Jump/Up". Для того, чтобы выполнить эту команду,
нужно ввести строку "/JU".
.PP
Перед некоторыми командами можно задавать целочисленный параметр,
определяющий, сколько раз нужно повторить данную команду.
.PP
При удалении строк или столбцов из таблицы все ссылки на удаляемые
клетки оказываются "висячими" и выглядят в формуле как "??".
.PP
При вычислении формул с висячими ссылками
или ссылками на клетки с ошибками вычисления также возникает ошибка.
.PP
Система команд:
.IP /Area/
переход в меню работы с областями (областью считается прямоугольный
участок таблицы от помеченной клетки до текущей)
.IP /Area/Copy
копирование области
.IP /Area/Delete
удаление области
.IP /Area/Format/
переход в меню установки формата
.IP /Area/Format/Center
центрирование клеток в области
.IP /Area/Format/Default
установка формата по умолчанию
.IP /Area/Format/Leftalign
установка прижима влево
.IP /Area/Format/Mark
установка метки на текущую клетку
.IP /Area/Format/Precision
задание точности для клеток в области
.IP /Area/Format/Rightalign
установка прижима вправо
.IP /Area/Mark
установка метки на текущую клетку
.IP /Area/Undelete
восстановление удаленной области
.IP /Area/Valuize
удаление формул из клеток в области (остаются только значения)
.IP /Area/fIll
заполнение области константами с заданными начальным значением и шагом
.IP /Cell/
переход в меню работы с отдельными ячейками
.IP /Cell/Copy
копирование помеченной ячейки в текущую
.IP /Cell/Delete
удаление содержимого текущей клетки
.IP /Cell/Format/
переход в меню установки формата
.IP /Cell/Format/Center
центрирование
.IP /Cell/Format/Default
установка формата по умолчанию
.IP /Cell/Format/Leftalign
установка прижима влево
.IP /Cell/Format/Mark
установка метки на текущую клетку
.IP /Cell/Format/Precision
задание точности
.IP /Cell/Format/Rightalign
установка прижима вправо
.IP /Cell/Mark
установка метки на текущую клетку
.IP /Cell/Undelete
восстановление удаленной клетки
.IP /File/
переход в меню работы с файлами
.IP /File/Load
загрузка таблицы из файла
.IP /File/Merge
слияние текущей таблицы и таблицы из файла
.IP /File/Print
печать таблицы в файл
.IP /File/Save
запись таблицы в файл
.IP /File/Tbl
запись таблицы в файл в формате
.B tbl
.IP /File/plOt
запись графика в файл в формате
.B plot
.IP /Graph/
переход в меню установки данных для графика
.IP /Graph/Hardcopy
печать графика на принтере
.IP /Graph/Mark
установка метки на текущую клетку
.IP /Graph/Reset
сброс установленных данных
.IP /Graph/Shape/
переход в меню установки типа графика
.IP /Graph/Shape/Bar
установка типа графика - столбчатая гистограмма
.IP /Graph/Shape/Graph
установка типа графика - линейный график
.IP /Graph/Shape/Pie
установка типа графика - круговая диаграмма
.IP /Graph/Shape/Stackedbar
установка типа графика - совмещенная гистограмма
.IP /Graph/Shape/X-y
установка типа графика - линейный график с нелинейной осью аргумента
.IP /Graph/axisA
установка данных для оси аргумента (область от помеченной клетки до текущей)
.IP /Graph/axisB
установка данных 1-й функции
.IP /Graph/axisC
установка данных 2-й функции
.IP /Graph/axisD
установка данных 3-й функции
.IP /Jump/
переход в меню передвижения по таблице
.IP /Jump/Cell
перейти на ячейку по имени
.IP /Jump/Down
перейти к последней клетке в текущем столбце
.IP /Jump/End
перейти к последней клетке таблицы
.IP /Jump/Left
перейти к первой ячейке в текущей строке
.IP /Jump/Right
перейти к последней ячейке в текущей строке
.IP /Jump/Up
перейти к первой ячейке в текущем столбце
.IP /Quit
выход из
.B ШЭТ
.IP /Row/
переход в меню работы со строками
.IP /Row/Copy
дублирование текущей строки
.IP /Row/Delete
удаление текущей строки
.IP /Row/Format/
переход в меню установки формата
.IP /Row/Format/Center
центрирование клеток в строке
.IP /Row/Format/Default
установка формата по умолчанию
.IP /Row/Format/Leftalign
установка прижима влево
.IP /Row/Format/Mark
установка метки на текущую клетку
.IP /Row/Format/Precision
задание точности для клеток в строке
.IP /Row/Format/Rightalign
установка прижима вправо
.IP /Row/Hide
спрятать текущую строку
.IP /Row/Insert
вставка пустой строки
.IP /Row/Show
открыть спрятанные строки
.IP /Row/Undelete
вернуть удаленную строку
.IP /Row/Valuize
заменить формулы в текущей строке значениями
.IP /Utility/
переход в меню сервисных команд
.IP /Utility/Width
установка количества столбцов в таблице
.IP /Utility/Height
установка количества строк в таблице
.IP /Utility/Minimize
уменьшение таблицы до минимально возможных размеров
.IP /Utility/Recalc
перевычисление таблицы
.IP /Utility/Autocalc
установка/снятие режима автоматического перевычисления
.IP /Utility/Border
установка/снятие режима отрисовки границы окна таблицы
.IP /Utility/Language
переключение языка команд/сообщений
.IP /Utility/Precision
установка точности по умолчанию
.IP /cOlumn/
переход в меню работы со строками
.IP /cOlumn/Copy
дублирование текущего столбца
.IP /cOlumn/Delete
удаление текущего столбца
.IP /cOlumn/Format/
переход в меню установки формата
.IP /cOlumn/Format/Center
центрирование клеток в столбце
.IP /cOlumn/Format/Default
установка формата по умолчанию
.IP /cOlumn/Format/Leftalign
установка прижима влево
.IP /cOlumn/Format/Mark
установка метки на текущую клетку
.IP /cOlumn/Format/Precision
задание точности для клеток в столбце
.IP /cOlumn/Format/Rightalign
установка прижима вправо
.IP /cOlumn/Hide
спрятать текущий столбец
.IP /cOlumn/Insert
вставка пустого столбца
.IP /cOlumn/Show
открыть спрятанные столбцы
.IP /cOlumn/Undelete
вернуть удаленный столбец
.IP /cOlumn/Valuize
заменить формулы в текущем столбце значениями
.IP /cOlumn/Width
установка ширины текущего столбца
.PP
Синтаксис формульных выражений близок к математической записи.
Приоритет операций следующий (от высшего к низшему):
^; *,/; +,-; <,=,>,<=,>=; &; |; ?.
.TP 15
e + e
Сложение.
.TP 15
e - e
Вычитание.
.TP 15
e * e
Умножение.
.TP 15
e / e
Деление.
.TP 15
e ^ e
Возведение в степень.
.TP 15
-e
Унарный минус.
.TP 15
e'
Возведение в квадрат.
.TP 15
~e
Квадратный корень.
.TP 15
v ++ v
Сумма всех непустых клеток в области с указанными углами.
.TP 15
v -- v
Среднее всех непустых клеток в области с указанными углами.
.TP 15
v ** v
Произведение всех непустых клеток в области с указанными углами.
.TP 15
v // v
Количество непустых клеток в области.
.TP 15
e ? e : e
Условная операция: если первое выражение - не 0, то значением операции
является значение второго выражения, иначе - значение третьего выражения.
.TP 15
<, =, >, <=, >=
Условные операции: 1 если выражение истинно, иначе 0.
.TP 15
&, |
Логические связки.
.TP 15
!e
Операция логического отрицания.
.TP 15
$v
защита ссылки от коррекции при перемещении выражения.
.PP
Разнообразные математические функции.
Большей частью это стандартные библиотечные функции,
более полно описанные в
.I math(3).
Все они оперируют с плавающими числами двойной точности,
тригонометрические функции работают с углами,
выраженными в радианах.
.TP 15
exp (expr)
Возвращает значение e в степени expr.
.TP 15
ln (expr)
Возвращает натуральный логарифм expr.
.TP 15
log (expr)
Возвращает десятичный логарифм expr.
.TP 15
pow (expr1, expr2)
Возвращает expr1 в степени expr2.
.TP 15
floor (expr)
Возвращает максимальное целое, не превосходящее expr.
.TP 15
ceil (expr)
Возвращает минимальное целое, не меньшее expr.
.TP 15
hypot (x, y)
Возвращает ~( x' + y' ), предпринимая меры против переполнения.
.TP 15
fabs (expr)
Возвращает абсолютное значение |expr|.
.TP 15
sin (expr), cos (expr), tan (expr)
Возвращает тригонометрическую функцию аргумента.
.TP 15
asin (expr)
Возвращает arcsin в диапазоне -pi/2...pi/2.
.TP 15
acos (expr)
Возвращает arccos в диапазоне 0...pi.
.TP 15
atan (expr)
Возвращает arctg в диапазоне -pi/2...pi/2.
.TP 15
dtr (expr)
Преобразует expr из градусов в радианы.
.TP 15
rtd (expr)
Преобразует expr из радианов в градусы.
.TP 15
pi
Примерно 3.1415926535...
.TP 15
e
Примерно 2.718281828459...
.TP 15
max (expr1, expr2)
Возвращает наибольшее из двух значений.
Допускается произвольное количество параметров.
.TP 15
min (expr1, expr2)
Возвращает наименьшее из двух значений.
Допускается произвольное количество параметров.
.TP 15
gamma (expr1)
Возвращает натуральный логарифм гамма-функции.
.SH ССЫЛКИ
bc(1), dc(1)
